### ISSUE TITLE
The front-end-server on Azure needs to serve a static URL for React-Router to work since Front-end is a Single-page-application

### ISSUE THREAD

**Issue by StahlErik** [pumpumba/Influsion-front-end#102]

**Comment by StahlErik** [comment]
Looking into fixing this etiher by Docker proxies or some kind of web.config-file

**Comment by StahlErik** [comment]
This seems to partially work now. However, routing to a 404-page is not yet implemented. Advice on how this could be done? Is a 404-page implemented?

**Comment by codebyjonas** [comment]
The 404 page is not fully implemented just created, so I will close this issue and focus on the 404.
