### ISSUE TITLE
The following page looks quite weird if you're not following anyone

### ISSUE THREAD

**Issue by StahlErik** [pumpumba/Influsion-front-end#111]
![image](https://user-images.githubusercontent.com/22325129/49025086-323ec700-f19b-11e8-99dd-2036abf0bfe9.png)

**Comment by ojaoweir** [comment]
Update with better text, for example: You do not follow any influencer yet. Press the [heart] on the startpage to follow a influencer
Also some styling, for example center the text.

**Comment by codebyjonas** [comment]
This is prio @linneawsjogren or @m-hakkestad
