### ISSUE TITLE
Bill Gates crashes app, both by search and following in feed. (Might be Back-end problem)

### ISSUE THREAD

**Issue by StahlErik** [pumpumba/Influsion-front-end#112]
![image](https://user-images.githubusercontent.com/22325129/49026454-35878200-f19e-11e8-8e8f-d6ec1da8adc7.png)
Following Bill Gates and going to follower page, or searching for Bill Gates and clicking him crashes the app. I've found no other Influenser that does this, but only tried 10 others or so.
This problem might very well be back-end

**Comment by Ludaestro** [comment]
What API call is being used in order to get the Bill Gates information?

**Comment by codebyjonas** [comment]
It is a front-end problem, works in Postman, extremely strange bug though.

**Comment by m-hakkestad** [comment]
Since every other influencer seems to work. Should we just remove Bill Gates?

**Comment by codebyjonas** [comment]
@ElonB  remove Bill Gates. please
