### ISSUE TITLE
Twitter text goes outside box

### ISSUE THREAD

**Issue by ojaoweir** [pumpumba/Influsion-front-end#115]
![image](https://user-images.githubusercontent.com/35972947/49069213-f7837000-f228-11e8-85ed-2748681c0e2d.png)
The question mark is cut by the edge of the content box

**Comment by linneawsjogren** [comment]
As of now I cant find any post that overflows, assumes it has been fixed before - seems resonable looking at the scss :)

**Comment by m-hakkestad** [comment]
![image](https://user-images.githubusercontent.com/42771492/49434783-56ab2c80-f7b5-11e8-959c-03e2d8288314.png)
![image](https://user-images.githubusercontent.com/42771492/49434788-59a61d00-f7b5-11e8-8b2d-a507b5b12f3c.png)

**Comment by m-hakkestad** [comment]
In following feed the twitter text goes outside box
