### ISSUE TITLE
Backing from twitter completely disrupts the platform

### ISSUE THREAD

**Issue by ojaoweir** [pumpumba/Influsion-front-end#118]
If you enter twitter by clicking their icon and then pressing back in the browser the application is completely broken. It open the wrong posts when clicked, several buttons do not work and so on.

**Comment by ojaoweir** [comment]
Same with instagram and youtube

**Comment by codebyjonas** [comment]
Please provide more information, I do not get this error.

**Comment by m-hakkestad** [comment]
What do we do with this @codebyjonas

**Comment by ojaoweir** [comment]
I cannot seem to recreate this issue, it has probably been fixed. 
Feel free to close this issue.
