### ISSUE TITLE
Changing account settings does not work?

### ISSUE THREAD

**Issue by ojaoweir** [pumpumba/Influsion-front-end#123]
No confirmation if it actually works, shows error in browser console

**Comment by m-hakkestad** [comment]
The db call always returns "updateSuccess": true. Even when password is wrong or an userid that doesn't exsist is used

**Comment by ojaoweir** [comment]
Is there a issue for this placed at the backend repo?

**Comment by ojaoweir** [comment]
Yes, backend #151
