### ISSUE TITLE
Cannot play youtube?

### ISSUE THREAD

**Issue by ojaoweir** [pumpumba/Influsion-front-end#126]
Cannot start playing youtube video on chrome on desktop. Works fine on phone though. Maybe something to look at?

**Comment by codebyjonas** [comment]
Please provide more information, It works on my computer.

**Comment by m-hakkestad** [comment]
I cant play youtube while in iphoneX mode in browser. When i click play it just minimizes to closed view again.

**Comment by codebyjonas** [comment]
I do not get this issue when mimicking your situation, please provide more information or close.

**Comment by m-hakkestad** [comment]
This is a problem with DevTOols zoom, not a real problem.
