### ISSUE TITLE
Register page only looks good on iPhoneX

### ISSUE THREAD

**Issue by ojaoweir** [pumpumba/Influsion-front-end#139]
![image](https://user-images.githubusercontent.com/35972947/49075211-aa0dff80-f236-11e8-965b-5ad7fe8889eb.png)
I know requirement says it should be designed for iPhoneX, but wuold be nice if it looked good on all phones because not everyone at presentations will have iPhoneX.

Fix if you have time over!

**Comment by codebyjonas** [comment]
What on the screenshot does not look nice? 
I do understand what's wrong.

**Comment by ojaoweir** [comment]
The formatting on the return to login button is weird. It is squeezed, if you compare with iPhoneX version you see that one has a nice button for it.
