### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by ojaoweir** [pumpumba/Influsion-front-end#68]
After registering, the page shows you a button that says sign in. When i click that one I am redirected to this URL: http://13.93.37.179/login. But that page is _not available_

Assigning to Jonas so he can direct it to whoever should take it.

**Comment by StahlErik** [comment]
This will work when routing in #102 is fully solved

**Comment by codebyjonas** [comment]
I would like to close this one. The problem is now the 404 page.
