### ISSUE TITLE
User icon on youtube content is the video picture

### ISSUE THREAD

**Issue by StahlErik** [pumpumba/Influsion-front-end#69]
![image](https://user-images.githubusercontent.com/22325129/48582312-7b358680-e924-11e8-8928-8d0a48403a37.png)
As shown in picture, MKBHD's icon on twitter is correct, but his icon on youtube is the still picture from the video

**Comment by codebyjonas** [comment]
Waiting for right url from backend

**Comment by StahlErik** [comment]
Is this solved?
