### ISSUE TITLE
Clicking on influencer name while at their page

### ISSUE THREAD

**Issue by ojaoweir** [pumpumba/Influsion-front-end#93]
If you have searched for a influencer, or clicked their name in feed, and then click on their name on a post you get redirected to a nonexisting page:
![image](https://user-images.githubusercontent.com/35972947/48847521-10f86800-eda2-11e8-8181-e584ccc50d34.png)

**Comment by m-hakkestad** [comment]
Right now pressing on an influencer name while on influence page tries to reroute them to url/infl/main.js need to reroute to url/main.js or not reroute at all

**Comment by codebyjonas** [comment]
Please solve @m-hakkestad
