### ISSUE TITLE
There is no scroll on modal on popular

### ISSUE THREAD

**Issue by codebyjonas** [pumpumba/Influsion-front-end#97]
Fix this overflow issue: 
![screenshot 2018-11-22 at 14 02 53](https://user-images.githubusercontent.com/6302670/48904676-69416f80-ee5f-11e8-8cb7-4cac6a8fc5d3.png)

**Comment by m-hakkestad** [comment]
Works on mobile and iphone X mode. Do you want it to work in browser as well?

**Comment by codebyjonas** [comment]
Please provide proof this works, not on developmen right now

**Comment by m-hakkestad** [comment]
![image](https://user-images.githubusercontent.com/42771492/49427395-83eedf00-f7a3-11e8-8f82-f3818e4c6715.png)

**Comment by m-hakkestad** [comment]
No issue only issue when screen bigger than app
